# Generated by Django 5.1.2 on 2024-11-02 13:57

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    'last_name',
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    'default_phone_number',
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    'default_street_address1',
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    'default_street_address2',
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    'default_town_or_city',
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    'default_county',
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    'profile_image',
                    models.ImageField(
                        blank=True, null=True, upload_to='profile_images/'
                    ),
                ),
                (
                    'default_postcode',
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    'default_country',
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('wish_list', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
